import type { ArtistInfo } from "@/lib/artist-info"

// Generated by scripts/generate-artist-info-db.mjs.
// Do not edit manually; rerun `npm run import:artist-info` to refresh imported artist metadata.
export const artistInfoDatabase: Record<string, ArtistInfo> = {}
