import type { ArtistInfo } from "@/lib/artist-info"

// Generated by scripts/import-artist-info-from-excel.mjs from Dekmantel artist biographies sheet.
// Rerun: npm run import:artist-info -- "/path/to/Dekmantel Schedule.xlsx"
export const artistInfoDatabase: Record<string, ArtistInfo> = {
  "A Guy Called Gerald presents Black Secret Technology live": {
    "bio": "Manchester producer A Guy Called Gerald links acid house, jungle and breakbeat history through a catalogue that reaches back to the late 1980s. This entry focuses on Black Secret Technology, the 1995 album where his drum-and-bass ideas became more spacious, atmospheric and forward-looking.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=A%20Guy%20Called%20Gerald",
    "sourceUrl": "https://dekmantelfestival.com/artists/a-guy-called-gerald-presents-black-secret-technology-live",
    "soundcloudUrl": "https://soundcloud.com/aguycalledgerald",
    "isLive": true
  },
  "Actress & Carl Craig": {
    "bio": "This pairing places Carl Craig’s Detroit-rooted techno language beside Actress’s more abstract UK approach to rhythm and texture. Rather than a conventional back-to-back, the collaboration reads as a meeting of two different electronic lineages: Craig’s expansive futurism and Actress’s fractured club experimentalism.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Actress%20Carl%20Craig",
    "sourceUrl": "https://dekmantelfestival.com/artists/carl-craig-actress",
    "soundcloudUrl": "https://soundcloud.com/actress1\nhttps://soundcloud.com/carlcraignet"
  },
  "Al Wootton & Azu Tiwaline": {
    "bio": "Al Wootton & Azu Tiwaline join ritual low-end pressure with dubwise and experimental club forms. Azu Tiwaline brings Amazigh and Sahrawi reference points into the collaboration, while Al Wootton adds the texture and weight of British bass music.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Al%20Wootton%20Azu%20Tiwaline",
    "sourceUrl": "https://dekmantelfestival.com/artists/azu-tiwaline-al-wootton",
    "soundcloudUrl": "https://soundcloud.com/alwootton\nhttps://soundcloud.com/azu-tiwaline"
  },
  "Alex Wilcox live": {
    "bio": "Alex Wilcox is a Dallas-born producer now based in Berlin after time in Austin, LA and Detroit. His music pushes techno through pop, electroclash, hardcore and punk influences, with vocal experimentation and collaborations playing a central role in his high-speed live sound.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Alex%20Wilcox%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/alex-wilcox-live",
    "soundcloudUrl": "https://soundcloud.com/alexwilcoxx",
    "isLive": true
  },
  "Amoral": {
    "bio": "AMORAL is an Amsterdam techno artist linked to Berghain, New York’s BASEMENT and the Eerste Communie event series. Her sound is rolling, vibrant and euphoric, with a careful sense of pressure that keeps the dancefloor moving without losing detail.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=AMORAL",
    "sourceUrl": "https://dekmantelfestival.com/artists/amoral-2",
    "soundcloudUrl": "https://soundcloud.com/amoralish"
  },
  "At Dawn: Channel One": {
    "bio": "Channel One is a DJ and MC operating across dub, bass and reggae. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Channel%20One",
    "sourceUrl": "https://dekmantelfestival.com/artists/channel-one",
    "soundcloudUrl": "https://soundcloud.com/channeloneofficial"
  },
  "At Dawn: Colin Benders": {
    "bio": "Colin Benders is a Dutch modular-synth artist and live performer who first became widely known as Kyteman. His techno work is built around hardware improvisation, combining raw rhythmic tension with hypnotic, meditative sound design.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Colin%20Benders",
    "sourceUrl": "https://dekmantelfestival.com/artists/colin-benders",
    "soundcloudUrl": "https://soundcloud.com/colinbenders"
  },
  "At Dawn: DJ Sprinkles' Deeperama": {
    "bio": "In electro, DJ Sprinkles' Deeperama has built a profile as a DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=DJ%20Sprinkles'%20Deeperama",
    "sourceUrl": "https://dekmantelfestival.com/artists/dj-sprinkles-deeperama",
    "soundcloudUrl": "https://soundcloud.com/djsprinkles-music"
  },
  "At Dawn: Eris Drew's Mystery of the Motherbeat": {
    "bio": "Eris Drew presents Mystery of the Motherbeat is an electronic music artist operating across house. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Eris%20Drew",
    "sourceUrl": "https://dekmantelfestival.com/artists/eris-drew-presents-mystery-of-the-motherbeat",
    "soundcloudUrl": "https://soundcloud.com/eris-drew"
  },
  "At Dawn: James Holden & Surgeon live": {
    "bio": "James Holden & Surgeon (opening ceremony) is a collaborative project, label founder and founder operating across techno, electro, ambient and trance. This appearance is centred on a live format, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=James%20Holden%20Surgeon%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/james-holden-surgeon-live",
    "soundcloudUrl": "https://soundcloud.com/jamesholden\nhttps://soundcloud.com/dynamic-tension",
    "isLive": true
  },
  "At Dawn: Jane Fitz presents Morning Colours": {
    "bio": "In techno, ambient and downtempo, Jane Fitz presents Morning Colours has built a profile as a DJ. This appearance is centred on a named project, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Jane%20Fitz",
    "sourceUrl": "https://dekmantelfestival.com/artists/jane-fitz-presents-morning-colours",
    "soundcloudUrl": "https://soundcloud.com/janefitz"
  },
  "At Dawn: Jeff Mills": {
    "bio": "Jeff Mills is a Detroit techno pioneer and one of electronic music’s most influential DJs and producers. His work is associated with precision, futurism and conceptual performance, from Underground Resistance history to expansive solo projects across club and experimental contexts.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Jeff%20Mills",
    "sourceUrl": "https://dekmantelfestival.com/artists/jeff-mills-debuts-stargate",
    "soundcloudUrl": "https://soundcloud.com/axis-jeff-mills"
  },
  "At Dawn: Kuniyuki & Satoshi Tomiie live": {
    "bio": "Kuniyuki and Satoshi Tomiie are Japanese electronic musicians with deep ties to house, techno and ambient music. Kuniyuki is known for textural, wide-ranging productions from Sapporo, while Tomiie has shaped international underground house through records, remixes and labels.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Kuniyuki%20Satoshi%20Tomiie%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/kuniyuki-satoshi-tomiie-live",
    "soundcloudUrl": "https://soundcloud.com/kuniyuki-1\nhttps://soundcloud.com/satoshitomiie",
    "isLive": true
  },
  "At Dawn: RA In Conversation": {
    "bio": "RA In Conversation is Resident Advisor’s interview and discussion format inside the festival programme. The item is not a DJ or live act; it is a context-led session around artists, scenes and club culture.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=RA%20In%20Conversation"
  },
  "At Dawn: Sampha DJ set": {
    "bio": "Sampha is a DJ operating across electro, pop and club music. This appearance is centred on a DJ set, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Sampha%20DJ%20set",
    "sourceUrl": "https://dekmantelfestival.com/artists/sampha-dj-set",
    "soundcloudUrl": "https://soundcloud.com/samphamusic",
    "isLive": false
  },
  "At Dawn:RA In Conversation": {
    "bio": "RA In Conversation is Resident Advisor’s interview and discussion format inside the festival programme. The item is not a DJ or live act; it is a context-led session around artists, scenes and club culture.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=RA%20In%20Conversation"
  },
  "Aurora Halal": {
    "bio": "In techno, experimental and psychedelic, Aurora Halal has built a profile as a DJ and producer. Reference points around the act include Sustain-Release, Mutual Dreaming and De School, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Aurora%20Halal",
    "sourceUrl": "https://dekmantelfestival.com/artists/aurora-halal",
    "soundcloudUrl": "https://soundcloud.com/itsallhalal"
  },
  "Aya live": {
    "bio": "Aya is an experimental club artist whose work moves through fractured electronics, high-pressure rhythm and raw vocal presence. Her releases on labels including Tri Angle, Astral Plane and Wisdom Teeth connect emotional intensity with restless, physically charged club structures.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Aya%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/aya-live",
    "soundcloudUrl": "https://soundcloud.com/ya-yousry",
    "isLive": true
  },
  "Batu": {
    "bio": "Batu is a Bristol-rooted producer and the founder of Timedance. His music treats UK bass as a flexible framework, folding in polyrhythmic motion, elastic low end and a constant sense of forward momentum rather than repeating one fixed club formula.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Batu",
    "sourceUrl": "https://dekmantelfestival.com/artists/batu-2",
    "soundcloudUrl": "https://soundcloud.com/batuuk"
  },
  "Ben UFO": {
    "bio": "Ben UFO is a London DJ and co-founder of Hessle Audio, the label he runs with Pearson Sound and Pangaea. His sets are known for fast, precise movement across garage, grime, dubstep, bass and other UK-rooted club forms.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Ben%20UFO",
    "sourceUrl": "https://dekmantelfestival.com/artists/ben-ufo",
    "soundcloudUrl": "https://soundcloud.com/benufo"
  },
  "Ben UFO & Call Super & Objekt & Pariah": {
    "bio": "Ben UFO & Call Super & Objekt & Pariah is a collaborative project and DJ operating across techno, bass and club music. Reference points around the act include Hessle Audio, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Ben%20UFO%20Call%20Super%20Objekt%20Pariah",
    "sourceUrl": "https://dekmantelfestival.com/artists/ben-ufo-call-super-objekt-pariah",
    "soundcloudUrl": "https://soundcloud.com/benufo\nhttps://soundcloud.com/call-super\nhttps://soundcloud.com/keinobjekt\nhttps://soundcloud.com/pariah_uk"
  },
  "Benny Rodrigues": {
    "bio": "Benny Rodrigues is a Rotterdam DJ associated with high-energy house and techno. Under his original moniker he leans into groove, Detroit influence, minimal pressure and acid detail; under ROD he is known for a more direct techno sound.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Benny%20Rodrigues",
    "sourceUrl": "https://dekmantelfestival.com/artists/benny-rodrigues",
    "soundcloudUrl": "https://soundcloud.com/benny-rodrigues-853273148"
  },
  "Beste Hira": {
    "bio": "Beste Hira is an Istanbul-born, Amsterdam-based DJ with a classical background in cello and piano. Her club sound draws on fast, hypnotic and darker techno, using that musical training to shape detailed, immersive sets with a strong sense of momentum.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Beste%20Hira",
    "sourceUrl": "https://dekmantelfestival.com/artists/beste-hira",
    "soundcloudUrl": "https://soundcloud.com/beste-hira"
  },
  "Bitter Babe": {
    "bio": "Bitter Babe is a Miami-based DJ and producer associated with fast, percussive club music. Her sets connect Latin American rhythms, bass pressure and rave energy, reflecting the wider transatlantic exchange around contemporary Latin club sounds.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Bitter%20Babe",
    "sourceUrl": "https://dekmantelfestival.com/artists/bitter-babe",
    "soundcloudUrl": "https://soundcloud.com/bitterbabe"
  },
  "Blasha & Allatt": {
    "bio": "Blasha & Allatt approaches techno, house and rave from the standpoint of a collaborative project. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Blasha%20Allatt",
    "sourceUrl": "https://dekmantelfestival.com/artists/blasha-allatt-2",
    "soundcloudUrl": "https://soundcloud.com/blasha-thor\nhttps://soundcloud.com/allatt-845059074"
  },
  "Brodinski & Slikback": {
    "bio": "Brodinski & Slikback links Paris-born, LA-based Brodinski with Kenyan producer Slikback. The pairing connects rap-informed club experimentation, Bromance-era electro pressure and Slikback’s raw, percussive approach to contemporary bass and techno structures.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Brodinski%20Slikback",
    "sourceUrl": "https://dekmantelfestival.com/artists/brodinski-slikback",
    "soundcloudUrl": "https://soundcloud.com/brodinskiofficial\nhttps://soundcloud.com/freddymn"
  },
  "Cari Lekebusch presents Vector": {
    "bio": "Cari Lekebusch presents Vector is a producer operating across techno and rap. This appearance is centred on a named project, giving the project a more specific frame than a standard DJ slot. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Cari%20Lekebusch",
    "sourceUrl": "https://dekmantelfestival.com/artists/cari-lekebush-presents-vector-live",
    "soundcloudUrl": "https://soundcloud.com/carilekebusch",
    "isLive": true
  },
  "CCL": {
    "bio": "CCL approaches dub, rave and funk from the standpoint of a DJ. Reference points around the act include Dekmantel Records, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=CCL",
    "sourceUrl": "https://dekmantelfestival.com/artists/ccl-2",
    "soundcloudUrl": "https://soundcloud.com/ccl-url"
  },
  "CCL presents Invisible Cities": {
    "bio": "CCL is a DJ, organiser and record collector associated with Bristol, North American DIY scenes and Berlin. Invisible Cities frames their wide-ranging taste through organic percussion, ambient pressure, oddball groove and detailed club storytelling.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=CCL",
    "sourceUrl": "https://dekmantelfestival.com/artists/ccl-presents-invisible-cities",
    "soundcloudUrl": "https://soundcloud.com/ccl-url"
  },
  "Cheyanne Hudson": {
    "bio": "Cheyanne Hudson approaches dub from the standpoint of a DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Cheyanne%20Hudson",
    "sourceUrl": "https://dekmantelfestival.com/artists/cheyanne-hudson",
    "soundcloudUrl": "https://soundcloud.com/peenievageenie"
  },
  "Christian AB": {
    "bio": "Christian AB brings a Berlin-linked perspective to techno, house and electro, shaped by work as a DJ and producer. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Christian%20AB",
    "sourceUrl": "https://dekmantelfestival.com/artists/christian-ab",
    "soundcloudUrl": "https://soundcloud.com/christian_ab"
  },
  "Dasha Rush & Oscar Mulero": {
    "bio": "Dasha Rush & Oscar Mulero approaches techno and experimental from the standpoint of a collaborative project. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dasha%20Rush%20Oscar%20Mulero",
    "sourceUrl": "https://dekmantelfestival.com/artists/dasha-rush-oscar-mulero",
    "soundcloudUrl": "https://soundcloud.com/dasha-rush\nhttps://soundcloud.com/oscarmulero"
  },
  "Dave Huismans (Ex_Libris, A Made Up Sound)": {
    "bio": "In techno, house, dub and club music, Dave Huismans (ex_libris, A Made Up Sound) has built a profile as a DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dave%20Huismans",
    "sourceUrl": "https://dekmantelfestival.com/artists/dave-huisman-ex-libris-a-made-up-sound",
    "soundcloudUrl": "https://soundcloud.com/amadeupsoundofficial"
  },
  "Dax J live": {
    "bio": "Dax J is a London-born techno DJ and producer associated with high-intensity, industrial-edged club music. Through releases on his Monnom Black imprint and appearances at institutions such as Berghain and Bassiani, he has built a reputation for forceful, tightly engineered sets.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dax%20J%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/dax-j-live",
    "soundcloudUrl": "https://soundcloud.com/daxj",
    "isLive": true
  },
  "Dekmantel Soundsystem": {
    "bio": "Dekmantel Soundsystem approaches techno, house, dub and funk from the standpoint of a selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dekmantel%20Soundsystem",
    "sourceUrl": "https://dekmantelfestival.com/artists/dekmantel-soundsystem"
  },
  "Dimi Angélis": {
    "bio": "Dimi Angélis is a Dutch DJ and producer shaped by warehouse parties, illegal raves and long-running techno practice. His sets connect classic drive with contemporary pressure, often moving through house, electro and rave references without losing a direct sense of propulsion.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dimi%20Ang%C3%A9lis",
    "sourceUrl": "https://dekmantelfestival.com/artists/dim-angélis",
    "soundcloudUrl": "https://soundcloud.com/dimi-angelis"
  },
  "Dino Sabatini & Luigi Tozzi live": {
    "bio": "Dino Sabatini & Luigi Tozzi is a collaborative project operating across dub techno, techno, ambient and dub. This appearance is centred on a live format, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dino%20Sabatini%20Luigi%20Tozzi%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/luigi-tozzi-dino-sabbatini-live",
    "soundcloudUrl": "https://soundcloud.com/dino-sabatini\nhttps://soundcloud.com/luigitozzi",
    "isLive": true
  },
  "Dirtylang": {
    "bio": "DirtyLang brings together Rotterdam DJs Dirtydms and Helmond Lang. Their profile points toward a bass-led sound that can move through ambient pressure, grime energy and leftfield club material without settling into one fixed lane.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=DirtyLang",
    "sourceUrl": "https://dekmantelfestival.com/artists/dirtylang"
  },
  "DJ Koolt": {
    "bio": "DJ Koolt is a Montevideo DJ and co-founder of Phonotheque, a club central to Uruguay’s minimalist dance music scene. His vinyl-led sound draws from acid, breaks, techno and avant-garde electronics, often with spacious textures and industrial edges.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=DJ%20Koolt",
    "sourceUrl": "https://dekmantelfestival.com/artists/dj-koolt-2",
    "soundcloudUrl": "https://soundcloud.com/dj-koolt"
  },
  "DJ Nobu & Wata Igarashi": {
    "bio": "DJ Nobu & Wata Igarashi is a collaborative project and DJ operating across techno. Reference points around the act include Dekmantel Records, which helps place the music in a broader club and label context. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=DJ%20Nobu%20Wata%20Igarashi",
    "sourceUrl": "https://dekmantelfestival.com/artists/dj-nobu-wata-igarashi",
    "soundcloudUrl": "https://soundcloud.com/djnobu_bitta\nhttps://soundcloud.com/wata"
  },
  "DJ Spanish Fly": {
    "bio": "DJ Spanish Fly, born Antonio Kimbrough, helped shape the early Memphis rap and club sound. His raw mixtapes, 808-heavy rhythms and house-DJ background connect local dance culture with the slower, darker Southern rap language that later travelled worldwide.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dj%20Spanish%20Fly",
    "sourceUrl": "https://dekmantelfestival.com/artists/dj-spanish-fly",
    "soundcloudUrl": "https://soundcloud.com/djspanishfly"
  },
  "Dopplereffekt": {
    "bio": "Dopplereffekt is an electronic music artist operating across techno and electro. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dopplereffekt",
    "sourceUrl": "https://dekmantelfestival.com/artists/dopplereffekt",
    "soundcloudUrl": "https://soundcloud.com/dopplereffektofficial"
  },
  "Doudou MD": {
    "bio": "Doudou MD approaches techno, house, electro and dub from the standpoint of a singer and selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Doudou%20MD",
    "sourceUrl": "https://dekmantelfestival.com/artists/doudou-md-2",
    "soundcloudUrl": "https://soundcloud.com/doudou-md"
  },
  "Dr. Rubinstein & Ellen Allien": {
    "bio": "In techno, acid and pop, Dr. Rubinstein & Ellen Allien has built a profile as a collaborative project, label founder and founder. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Dr.%20Rubinstein%20Ellen%20Allien",
    "sourceUrl": "https://dekmantelfestival.com/artists/dr-rubinstein-ellen-allien",
    "soundcloudUrl": "https://soundcloud.com/dr-rubinstein\nhttps://soundcloud.com/ellen-allien"
  },
  "DVS1": {
    "bio": "DVS1 is a DJ operating across techno and electro. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=DVS1",
    "sourceUrl": "https://dekmantelfestival.com/artists/dvs1",
    "soundcloudUrl": "https://soundcloud.com/dvs1"
  },
  "Efdemin & Polygonia": {
    "bio": "Efdemin & Polygonia approaches techno, ambient, minimal and rap from the standpoint of a collaborative project. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Efdemin%20Polygonia",
    "sourceUrl": "https://dekmantelfestival.com/artists/efdemin-polygonia",
    "soundcloudUrl": "https://soundcloud.com/efdemin\nhttps://soundcloud.com/polygonia"
  },
  "Eris Drew & Octo Octa": {
    "bio": "In techno, house, electro and breakbeat, Eris Drew & Octo Octa has built a profile as a collaborative project, DJ and producer. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Eris%20Drew%20Octo%20Octa",
    "sourceUrl": "https://dekmantelfestival.com/artists/octo-octa-eris-drew",
    "soundcloudUrl": "https://soundcloud.com/eris-drew\nhttps://soundcloud.com/octoocta"
  },
  "Fafi Abdel Nour & Jennifer Loveless": {
    "bio": "With links to Amsterdam, Fafi Abdel Nour & Jennifer Loveless works as a collaborative project and DJ in the space between techno, house and bass. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Fafi%20Abdel%20Nour%20Jennifer%20Loveless",
    "sourceUrl": "https://dekmantelfestival.com/artists/fafi-abdel-nour-jennifer-loveless",
    "soundcloudUrl": "https://soundcloud.com/fafi_abdel_nour\nhttps://soundcloud.com/jenniferloveless"
  },
  "FJAAK hybrid": {
    "bio": "FJAAK is a Berlin hardware-driven act whose music draws from techno, UK garage and breakbeat. The hybrid format suits their hands-on approach: machines, club history and rough-edged groove are treated as active parts of the performance rather than background references.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=FJAAK%20Hybrid",
    "sourceUrl": "https://dekmantelfestival.com/artists/fjaak-hybrid",
    "soundcloudUrl": "https://soundcloud.com/fjaak",
    "isLive": true
  },
  "Francois K & Suze Ijó": {
    "bio": "François K & Suze Ijó is a collaborative project, selector and collective connected to Chicago to the Caribbean, with a sound that moves through house. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Fran%C3%A7ois%20K%20Suze%20Ij%C3%B3",
    "sourceUrl": "https://dekmantelfestival.com/artists/françois-k-suze-ijó",
    "soundcloudUrl": "https://soundcloud.com/francoiskofficial\nhttps://soundcloud.com/suze_ijo"
  },
  "Fumiya Tanaka": {
    "bio": "Fumiya Tanaka approaches techno, house, electro and minimal from the standpoint of a DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Fumiya%20Tanaka",
    "sourceUrl": "https://dekmantelfestival.com/artists/fumiya-tanaka",
    "soundcloudUrl": "https://soundcloud.com/fumiyatanaka_official"
  },
  "Gabrielle Kwarteng": {
    "bio": "Gabrielle Kwarteng brings a Berlin-linked perspective to techno, house, electro and funk, shaped by work as a selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Gabrielle%20Kwarteng",
    "sourceUrl": "https://dekmantelfestival.com/artists/gabrielle-kwarteng",
    "soundcloudUrl": "https://soundcloud.com/gabriellekwarteng"
  },
  "Garçon & Sybil": {
    "bio": "Garçon & Sybil brings together two selectors with a taste for deep, patient and atmospheric club music. Garçon is linked to the Amenthia label and Japan’s Transcendence Festival, while Sybil’s sets move through dub, techno, breaks and trance-inflected forms.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Gar%C3%A7on%20Sybil",
    "sourceUrl": "https://dekmantelfestival.com/artists/garçon-sybil",
    "soundcloudUrl": "https://soundcloud.com/garcon\nhttps://soundcloud.com/syberkid"
  },
  "Gigi FM & Jako Jako": {
    "bio": "With links to Berlin, GiGi FM works as a collaborative project, DJ and producer in the space between techno, ambient, bass and rave. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=GiGi%20FM",
    "sourceUrl": "https://dekmantelfestival.com/artists/gigi-fm",
    "soundcloudUrl": "https://soundcloud.com/gigi-fm\nhttps://soundcloud.com/jako-jako-619622670"
  },
  "Gyrofield": {
    "bio": "Gyrofield, the project of Hong Kong-born Kiana Li, works at the outer edges of contemporary drum and bass. Her productions combine industrial weight, psychedelic detail and sharp rhythmic design, often shifting between high-speed pressure and more abstract structures.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Gyrofield",
    "sourceUrl": "https://dekmantelfestival.com/artists/gyrofield",
    "soundcloudUrl": "https://soundcloud.com/gyrofieldmusic"
  },
  "Helena Hauff & L.F.T.": {
    "bio": "Helena Hauff & L.F.T. is a collaborative project and producer operating across techno, electro and acid. Reference points around the act include Tresor, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Helena%20Hauff%20L.F.T.",
    "sourceUrl": "https://dekmantelfestival.com/artists/helena-hauff-lft",
    "soundcloudUrl": "https://soundcloud.com/helena-hauff\nhttps://soundcloud.com/lfttrax"
  },
  "Honduku": {
    "bio": "Konduku, listed here as Honduku, is a producer and DJ whose work sits in cerebral, rhythmically detailed techno. His sets and records often favour polyrhythmic movement, restraint and a precise sense of spatial pressure.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Konduku",
    "sourceUrl": "https://dekmantelfestival.com/artists/konduku",
    "soundcloudUrl": "https://soundcloud.com/kondukukonduku"
  },
  "Identified Patient": {
    "bio": "In techno, bass, acid and industrial, Identified Patient has built a profile as a DJ and producer. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Identified%20Patient",
    "sourceUrl": "https://dekmantelfestival.com/artists/identified-patient",
    "soundcloudUrl": "https://soundcloud.com/identified-patient"
  },
  "Ikonika": {
    "bio": "Ikonika is a DJ operating across dub, bass, garage and pop. Reference points around the act include Hyperdub, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Ikonika",
    "sourceUrl": "https://dekmantelfestival.com/artists/ikonika",
    "soundcloudUrl": "https://soundcloud.com/ikonika"
  },
  "Interstellar Funk": {
    "bio": "Interstellar Funk approaches house and funk from the standpoint of a founder, DJ and producer. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Interstellar%20Funk",
    "sourceUrl": "https://dekmantelfestival.com/artists/interstellar-funk",
    "soundcloudUrl": "https://soundcloud.com/interstellarfunk"
  },
  "Introspekt": {
    "bio": "In dub, bass, garage and rave, Introspekt has built a profile as an artist. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Introspekt",
    "sourceUrl": "https://dekmantelfestival.com/artists/introspekt",
    "soundcloudUrl": "https://soundcloud.com/sageintrospekt"
  },
  "James Massiah & Lord Tusk": {
    "bio": "James Massiah & Lord Tusk approaches house, electro, dub and minimal from the standpoint of a collaborative project. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=James%20Massiah%20Lord%20Tusk",
    "sourceUrl": "https://dekmantelfestival.com/artists/james-massiah-lord-tusk",
    "soundcloudUrl": "https://soundcloud.com/jamesmassiah\nhttps://soundcloud.com/user451387179"
  },
  "Jasmín": {
    "bio": "Jasmín is a Dutch DJ and producer with roots in Amsterdam’s club circuit and De School. Her Hessle Audio track “Bite the Hand” sharpened her profile, reflecting a sound built from percussive pressure, gloomy atmospheres and intricate genre-crossing club tracks.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Jasm%C3%ADn",
    "sourceUrl": "https://dekmantelfestival.com/artists/jasmín",
    "soundcloudUrl": "https://soundcloud.com/jasminhoek"
  },
  "JASSS & Vlada": {
    "bio": "JASSS & Vlada approaches techno, house, electro and ambient from the standpoint of a collaborative project and DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=JASSS%20Vlada",
    "sourceUrl": "https://dekmantelfestival.com/artists/jasss-vlada",
    "soundcloudUrl": "https://soundcloud.com/jass-29\nhttps://soundcloud.com/playvlada"
  },
  "Job Jobse & Palms Trax": {
    "bio": "Job Jobse & Palms Trax is a collaborative project and selector connected to Berlin, with a sound that moves through techno, house and trance. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Job%20Jobse%20Palms%20Trax",
    "sourceUrl": "https://dekmantelfestival.com/artists/job-jobse-palms-trax",
    "soundcloudUrl": "https://soundcloud.com/jobjobse\nhttps://soundcloud.com/palmstrax"
  },
  "Juan Atkins": {
    "bio": "Juan Atkins approaches techno, electro, rave and funk from the standpoint of a founder and DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Juan%20Atkins",
    "sourceUrl": "https://dekmantelfestival.com/artists/juan-atkins",
    "soundcloudUrl": "https://soundcloud.com/juan-atkins"
  },
  "Jyoty": {
    "bio": "Jyoty is an Amsterdam-born selector whose career grew through radio, clubs and international touring. Her sets are high-energy and open-ended, pulling from bass music, breaks, hip-hop, funk, grime and dancehall while keeping a clear sense of crowd connection.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Jyoty",
    "sourceUrl": "https://dekmantelfestival.com/artists/jyoty",
    "soundcloudUrl": "https://soundcloud.com/jyotysingh"
  },
  "Katatonic Silention": {
    "bio": "Katatonic Silentio is a DJ and producer operating across techno, electro, ambient and dub. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Katatonic%20Silentio",
    "sourceUrl": "https://dekmantelfestival.com/artists/katatonic-silentio",
    "soundcloudUrl": "https://soundcloud.com/katatonicsilentio"
  },
  "Khadija Al Hanafi hybrid": {
    "bio": "Khadija Al Hanafi approaches footwork, experimental, psychedelic and rap from the standpoint of a DJ and producer. This appearance is centred on a hybrid format, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Khadija%20Al%20Hanafi%20Hybrid",
    "sourceUrl": "https://dekmantelfestival.com/artists/khadija-al-hanafi-hybrid",
    "soundcloudUrl": "https://soundcloud.com/khadijaalhanafi",
    "isLive": true
  },
  "Kode9 presents Hyperdub": {
    "bio": "Kode9 is a DJ, producer, theorist and founder of Hyperdub, one of the defining UK labels for dubstep, bass music and experimental club culture. This project focuses on the label’s long catalogue, from landmark releases to deeper and more exploratory material.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Kode9",
    "sourceUrl": "https://dekmantelfestival.com/artists/kode9-presents-hyperdub",
    "soundcloudUrl": "https://soundcloud.com/kode9-1"
  },
  "Lady Starlight & Sterac live": {
    "bio": "With links to NYC, Lady Starlight & STERAC works as a collaborative project and producer in the space between techno, electro, acid and industrial. This appearance is centred on a live format, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Lady%20Starlight%20STERAC%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/lady-starlight-sterac-live",
    "soundcloudUrl": "https://soundcloud.com/ladystarlightnyc\nhttps://soundcloud.com/sterac",
    "isLive": true
  },
  "Lea Occhi": {
    "bio": "Lea Occhi is a French DJ based in Amsterdam, rooted in techno but open to micro-house, deep and ambient records. She co-founded Spectrum Waves in Paris, a queer collective focused on safer spaces and community, values that inform her atmospheric approach.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Lea%20Occhi",
    "sourceUrl": "https://dekmantelfestival.com/artists/lea-occhi",
    "soundcloudUrl": "https://soundcloud.com/lea-occhi"
  },
  "Livwutang": {
    "bio": "livwutang is an electronic music artist connected to NYC, with a sound that moves through techno, dub and rave. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=livwutang",
    "sourceUrl": "https://dekmantelfestival.com/artists/livwutang",
    "soundcloudUrl": "https://soundcloud.com/livwutang"
  },
  "Loradeniz": {
    "bio": "With links to Amsterdam, Loradeniz works as a DJ, producer and vocalist in the space between techno, house, ambient and bass. Reference points around the act include Nous’klaer, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Loradeniz",
    "sourceUrl": "https://dekmantelfestival.com/artists/loradeniz",
    "soundcloudUrl": "https://soundcloud.com/loradeniz"
  },
  "LSD live (Function & Luke Slater & Steve Bicknell)": {
    "bio": "In techno and dub, LSD (Function & Luke Slater & Steve Bicknell) has built a profile as a collaborative project and collective. Reference points around the act include Berghain, which helps place the music in a broader club and label context. The live format format keeps attention on the artist’s own material, catalogue or concept.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=LSD%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/lsd-live-luke-slater-steve-bicknell-function",
    "soundcloudUrl": "https://soundcloud.com/functionfm\nhttps://soundcloud.com/luke-slater\nhttps://soundcloud.com/steve-bicknell",
    "isLive": true
  },
  "Mad Miran & Quest": {
    "bio": "mad miran & Quest is a collaborative project and selector connected to Berlin and Barcelona, with a sound that moves through electro, IDM, rave and club music. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=mad%20miran%20Quest",
    "sourceUrl": "https://dekmantelfestival.com/artists/mad-miran-quest",
    "soundcloudUrl": "https://soundcloud.com/madmiran\nhttps://soundcloud.com/questwax"
  },
  "Makam presents The Archive live": {
    "bio": "Makam presents The Archive approaches techno, house and psychedelic from the standpoint of a DJ. Reference points around the act include Dekmantel Records, which helps place the music in a broader club and label context. The live format and named project format keeps attention on the artist’s own material, catalogue or concept.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Makam",
    "sourceUrl": "https://dekmantelfestival.com/artists/makam-presents-the-archive-live",
    "soundcloudUrl": "https://soundcloud.com/makam",
    "isLive": true
  },
  "Mala": {
    "bio": "In dub, bass and rave, Mala has built a profile as a DJ, producer and collective. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Mala",
    "sourceUrl": "https://dekmantelfestival.com/artists/mala",
    "soundcloudUrl": "https://soundcloud.com/maladmz"
  },
  "Mala & Sir Spyro": {
    "bio": "Mala & Sir Spyro is a collaborative project, DJ and producer operating across dub, bass and grime. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Mala%20Sir%20Spyro",
    "sourceUrl": "https://dekmantelfestival.com/artists/mala-sir-spyro",
    "soundcloudUrl": "https://soundcloud.com/maladmz\nhttps://soundcloud.com/djsirspyro"
  },
  "Marcel Dettmann": {
    "bio": "Marcel Dettmann approaches techno and house from the standpoint of a DJ. Reference points around the act include Berghain, which helps place the music in a broader club and label context. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Marcel%20Dettmann",
    "sourceUrl": "https://dekmantelfestival.com/artists/marcel-dettmann",
    "soundcloudUrl": "https://soundcloud.com/marceldettmann"
  },
  "Mia Koden": {
    "bio": "In techno, dub, bass and percussion, Mia Koden has built a profile as a selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Mia%20Koden",
    "sourceUrl": "https://dekmantelfestival.com/artists/mia-koden",
    "soundcloudUrl": "https://soundcloud.com/miakoden"
  },
  "Mike Parker live": {
    "bio": "Mike Parker is a techno producer and DJ known for hypnotic, tunnelling sound design and precise rhythmic architecture. His catalogue reaches across respected techno labels and his own Geophone imprint, with a live approach built around repetition, depth and pressure.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Mike%20Parker%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/mike-parker-live",
    "soundcloudUrl": "https://soundcloud.com/geophone",
    "isLive": true
  },
  "Nala Brown": {
    "bio": "Nala Brown is the DJ moniker of Rotterdam-born Jacqueline Monteiro. Her sets combine Detroit and New York club references, contemporary pop and R&B edits, high-energy percussion and influences connected to her Cape Verdean roots and AMPFEMININE nightlife work.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Nala%20Brown",
    "sourceUrl": "https://dekmantelfestival.com/artists/nala-brown",
    "soundcloudUrl": "https://soundcloud.com/nalabr0wn"
  },
  "Nazar hybrid": {
    "bio": "Nazar is a DJ operating across electro, bass and percussion. This appearance is centred on a hybrid format, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Nazar%20Hybrid",
    "sourceUrl": "https://dekmantelfestival.com/artists/nazar-hybrid",
    "soundcloudUrl": "https://soundcloud.com/nazareth-1",
    "isLive": true
  },
  "Neska": {
    "bio": "With links to Amsterdam via Barcelona, Neska works as a DJ in the space between electro, dub, punk and experimental. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Neska",
    "sourceUrl": "https://dekmantelfestival.com/artists/neska",
    "soundcloudUrl": "https://soundcloud.com/youngneska"
  },
  "Nicolas Lutz": {
    "bio": "Nicolas Lutz brings a Montevideo-linked perspective to techno, house and electro, shaped by work as a DJ and selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Nicolas%20Lutz",
    "sourceUrl": "https://dekmantelfestival.com/artists/nicolas-lutz",
    "soundcloudUrl": "https://soundcloud.com/nicolaslutz"
  },
  "Nicolini live": {
    "bio": "Nicolini is a band operating across dub and dancehall. This appearance is centred on a live format, giving the project a more specific frame than a standard DJ slot. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Nicolini%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/nicolini-live",
    "soundcloudUrl": "https://soundcloud.com/nicoliniskinni4people",
    "isLive": true
  },
  "Nídia": {
    "bio": "With links to Lisbon, Nídia works as a DJ and collective in the space between percussion. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=N%C3%ADdia",
    "sourceUrl": "https://dekmantelfestival.com/artists/nídia",
    "soundcloudUrl": "https://soundcloud.com/nidiasukulbembe"
  },
  "Niks": {
    "bio": "In techno, house, dub and bass, NIKS has built a profile as a DJ and producer. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=NIKS",
    "sourceUrl": "https://dekmantelfestival.com/artists/niks-2",
    "soundcloudUrl": "https://soundcloud.com/niksbad"
  },
  "Nørbak & Surgeon live": {
    "bio": "Nørbak & Surgeon pairs Portuguese producer Nørbak’s detailed, hypnotic sound design with Surgeon’s long-standing role in UK techno. The collaboration connects dense textures, controlled rhythmic pressure and a live-performance approach to abstract, high-intensity techno.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=N%C3%B8rbak%20Surgeon%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/nørbak-surgeon-live",
    "soundcloudUrl": "https://soundcloud.com/norbak-music\nhttps://soundcloud.com/dynamic-tension",
    "isLive": true
  },
  "Novelist & DJ Slimzee": {
    "bio": "Novelist & Dj Slimzee is a collaborative project and DJ operating across bass and grime. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Novelist%20Dj%20Slimzee",
    "sourceUrl": "https://dekmantelfestival.com/artists/dj-slimzee-novelist-live",
    "soundcloudUrl": "https://soundcloud.com/novelist\nhttps://soundcloud.com/user-23846772"
  },
  "Objekt": {
    "bio": "With links to The Berlin, Objekt works as a DJ and producer in the space between techno, ambient, bass and IDM. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Objekt",
    "sourceUrl": "https://dekmantelfestival.com/artists/objekt",
    "soundcloudUrl": "https://soundcloud.com/keinobjekt"
  },
  "Octo Octa DnB set": {
    "bio": "In techno, house and bass, Octo Octa () has built a profile as a co-founder, founder and DJ. This appearance is centred on a drum-and-bass set, giving the project a more specific frame than a standard DJ slot. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Octo%20Octa",
    "sourceUrl": "https://dekmantelfestival.com/artists/octo-octa-dnd-set",
    "soundcloudUrl": "https://soundcloud.com/octoocta",
    "isLive": false
  },
  "Ogazón & Philippa Pacho": {
    "bio": "Ogázon & Philippa Pacho is a collaborative project and DJ connected to Luxembourg via Amsterdam and Berlin, with a sound that moves through techno, house, electro and trance. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Og%C3%A1zon%20Philippa%20Pacho",
    "sourceUrl": "https://dekmantelfestival.com/artists/ogázon-philippa-pacho",
    "soundcloudUrl": "https://soundcloud.com/ogazon\nhttps://soundcloud.com/philippapacho"
  },
  "Olof Dreijer & Toya Delazy": {
    "bio": "With links to KwaZulu-Natal, Olof Dreijer & Toya Delazy works as a collaborative project in the space between drum & bass, techno, electro and bass. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Olof%20Dreijer%20Toya%20Delazy",
    "sourceUrl": "https://dekmantelfestival.com/artists/olof-dreijer-toya-delazy",
    "soundcloudUrl": "https://soundcloud.com/olofdreijer\nhttps://soundcloud.com/toya-delazy"
  },
  "Parallel 9 & Richard Akingbehin": {
    "bio": "In techno, ambient and dub, Parallel 9 & Richard Akingbehin has built a profile as a collaborative project, co-founder and founder. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Parallel%209%20Richard%20Akingbehin",
    "sourceUrl": "https://dekmantelfestival.com/artists/parallel-9-richard-akingbehin",
    "soundcloudUrl": "https://soundcloud.com/parallel9official\nhttps://soundcloud.com/richard-akingbehin"
  },
  "PLO Man & Skee Mask": {
    "bio": "PLO Man & Skee Mask is a collaborative project and selector operating across techno, jungle, ambient and breakbeat. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=PLO%20Man%20Skee%20Mask",
    "sourceUrl": "https://dekmantelfestival.com/artists/plo-man-skee-mask",
    "soundcloudUrl": "https://soundcloud.com/p_el_oh\nhttps://soundcloud.com/skeemask-music"
  },
  "Polygonia": {
    "bio": "Polygonia approaches techno, ambient and downtempo from the standpoint of an artist. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Polygonia",
    "sourceUrl": "https://dekmantelfestival.com/artists/polygonia",
    "soundcloudUrl": "https://soundcloud.com/polygonia"
  },
  "Rene Wise": {
    "bio": "Rene Wise is a DJ operating across techno, polyrhythms and percussion. Reference points around the act include Eerste Communie, Berghain and Pressure, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Rene%20Wise",
    "sourceUrl": "https://dekmantelfestival.com/artists/rene-wise",
    "soundcloudUrl": "https://soundcloud.com/renewise"
  },
  "RHR & Skrillex": {
    "bio": "RHR & Skrillex approaches electro, dub, rave and pop from the standpoint of a collaborative project, producer and selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=RHR%20Skrillex",
    "sourceUrl": "https://dekmantelfestival.com/artists/rhr-skrillex",
    "soundcloudUrl": "https://soundcloud.com/rhrmusiq\nhttps://soundcloud.com/skrillex"
  },
  "Ricardo Villalobos": {
    "bio": "Ricardo Villalobos is a Chilean-German DJ and producer closely associated with minimal house and techno. His sets are known for long-form blends, microscopic rhythmic detail and a loose, improvisational sense of groove that has shaped generations of selectors.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Ricardo%20Villalobos",
    "sourceUrl": "https://dekmantelfestival.com/artists/ricardo-villalobos",
    "soundcloudUrl": "https://soundcloud.com/ricardo-villalobos"
  },
  "Ron Trent presents La Marr w/ Paolo Color live": {
    "bio": "Ron Trent is a Chicago-rooted house producer whose work often links dance music with deep listening, spirituality and jazz-informed atmosphere. LA MARR with Pablo Color centres on an ambient live project, extending Trent’s catalogue beyond club tracks into expansive sound design.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Ron%20Trent",
    "sourceUrl": "https://dekmantelfestival.com/artists/ron-trent-live",
    "soundcloudUrl": "https://soundcloud.com/musicandpower\nhttps://soundcloud.com/pablocolor",
    "isLive": true
  },
  "Rozaly": {
    "bio": "Rozaly approaches electro, bass and percussion from the standpoint of a DJ and selector. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Rozaly",
    "sourceUrl": "https://dekmantelfestival.com/artists/rozaly",
    "soundcloudUrl": "https://soundcloud.com/rozalymusic"
  },
  "Ryan Elliott": {
    "bio": "Ryan Elliott is an American DJ associated with precise, functional house and techno. His work around Berlin club culture and Ostgut Ton has made him a reference point for selectors who value pacing, groove and direct dancefloor utility.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Ryan%20Elliott",
    "sourceUrl": "https://dekmantelfestival.com/artists/ryan-elliot",
    "soundcloudUrl": "https://soundcloud.com/ryan-elliott"
  },
  "Sandrien": {
    "bio": "With links to Japan to Tbilisi to far beyond, Sandrien works as a co-founder, founder and DJ in the space between techno and house. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Sandrien",
    "sourceUrl": "https://dekmantelfestival.com/artists/sandrien",
    "soundcloudUrl": "https://soundcloud.com/sandrien"
  },
  "Sass (Moxie & Peach & Saoirse & Shanti Celeste)": {
    "bio": "In techno, house, electro and bass, SASS (Moxie & Peach & Saoirse & Shanti Celeste) has built a profile as a collaborative project, DJ and collective. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=SASS",
    "sourceUrl": "https://dekmantelfestival.com/artists/sass-moxie-peach-saoirse-shanti-celeste",
    "soundcloudUrl": "https://soundcloud.com/ohpeach\nhttps://soundcloud.com/saoirsemusic\nhttps://soundcloud.com/shanticeleste"
  },
  "Scratchclart & State OFFF": {
    "bio": "Scratchclart, also known as Scratcha DVA, is a London DJ, producer and sound designer linked to pirate radio, Hyperdub and UK club music. State OFFF is a Zimbabwe-born, Amsterdam-based artist; together they connect grime, gqom, funk, amapiano and bass pressure.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Scratchclart%20State%20OFFF",
    "sourceUrl": "https://dekmantelfestival.com/artists/scratchclart-state-offf",
    "soundcloudUrl": "https://soundcloud.com/state-offf"
  },
  "Shed presents Rave Echoes live": {
    "bio": "Shed is the alias of Berlin producer René Pawlowitz, known for techno that connects warehouse force with dub weight and rave memory. Rave Echoes is presented as a live project around his Dekmantel label album of the same name.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Shed",
    "sourceUrl": "https://dekmantelfestival.com/artists/shed-presents-rave-echoes-live",
    "soundcloudUrl": "https://soundcloud.com/shedofficial",
    "isLive": true
  },
  "Sherelle": {
    "bio": "SHERELLE brings a DnB-linked perspective to techno, jungle, acid and footwork, shaped by work as a DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=SHERELLE",
    "sourceUrl": "https://dekmantelfestival.com/artists/sherelle",
    "soundcloudUrl": "https://soundcloud.com/iamsherelle"
  },
  "Shy FX & Tasha": {
    "bio": "Shy FX & Tasha is a collaborative project, founder and selector operating across techno, jungle, dub and bass. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Shy%20FX%20Tasha",
    "sourceUrl": "https://dekmantelfestival.com/artists/shy-fx-tasha",
    "soundcloudUrl": "https://soundcloud.com/shy-fx\nhttps://soundcloud.com/wowtashawow"
  },
  "Skin on Skin": {
    "bio": "With links to Brisbane to international stages, Skin On Skin works as a DJ in the space between techno, house, bass and club music. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Skin%20On%20Skin",
    "sourceUrl": "https://dekmantelfestival.com/artists/skin-on-skin",
    "soundcloudUrl": "https://soundcloud.com/skinonskin-music"
  },
  "Skrillex": {
    "bio": "In electro, dub, bass and pop, Skrillex has built a profile as an artist. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Skrillex",
    "sourceUrl": "https://dekmantelfestival.com/artists/skrillex",
    "soundcloudUrl": "https://soundcloud.com/skrillex"
  },
  "Speedy J": {
    "bio": "Speedy J is a founder, DJ and producer operating across techno, electro, ambient and industrial. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Speedy%20J",
    "sourceUrl": "https://dekmantelfestival.com/artists/speedy-j",
    "soundcloudUrl": "https://soundcloud.com/jochempaap"
  },
  "Steffi": {
    "bio": "Steffi approaches techno, house and electro from the standpoint of a DJ and collective. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Steffi",
    "sourceUrl": "https://dekmantelfestival.com/artists/steffi",
    "soundcloudUrl": "https://soundcloud.com/steffi_official"
  },
  "Sugar Free": {
    "bio": "Sugar Free is a DJ associated with stripped-down, rolling house and techno selections. The festival source did not include a longer biography, so this entry stays deliberately factual and compact.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Sugar%20Free",
    "sourceUrl": "https://dekmantelfestival.com/artists/sugar-free-2",
    "soundcloudUrl": "https://soundcloud.com/freesugarfree"
  },
  "T.NO": {
    "bio": "T.NO is a producer connected to Amsterdam right now, with a sound that moves through bass, grime, funk and percussion. Reference points around the act include TraTraTrax, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=T.NO",
    "sourceUrl": "https://dekmantelfestival.com/artists/t-no",
    "soundcloudUrl": "https://soundcloud.com/tdotno"
  },
  "The Black Dog live": {
    "bio": "The Black Dog is a Sheffield electronic group associated with Warp Records, early IDM and atmospheric techno. Releases such as Bytes and Spanners helped define a detailed, rhythmically intricate approach that continues through later ambient, techno and conceptual work.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=The%20Black%20Dog%20Live",
    "sourceUrl": "https://dekmantelfestival.com/artists/the-black-dog-live",
    "soundcloudUrl": "https://soundcloud.com/the-black-dog",
    "isLive": true
  },
  "The Bug & Warrior Queen": {
    "bio": "In dub, grime, dancehall and reggae, The Bug & Warrior Queen has built a profile as a collaborative project, singer and MC. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=The%20Bug%20Warrior%20Queen",
    "sourceUrl": "https://dekmantelfestival.com/artists/the-bug-warrior-queen",
    "soundcloudUrl": "https://soundcloud.com/thebugofficial\nhttps://soundcloud.com/ann-martin-721565168"
  },
  "Tikiman live w/ Scion": {
    "bio": "Tikiman is vocalist Paul St. Hilaire, closely tied to dub techno through a voice shaped by reggae and dub traditions. Scion unites René Löwe and Peter Kuschnereit, two Berlin figures connected to Chain Reaction, Basic Channel and Tresor.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Tikiman%20Live%20w%2F%20Scion",
    "sourceUrl": "https://dekmantelfestival.com/artists/tikiman-live-with-scion",
    "soundcloudUrl": "https://soundcloud.com/paulsthilaire\nhttps://soundcloud.com/scion_music_official",
    "isLive": true
  },
  "Trickpony": {
    "bio": "trickpony approaches trip-hop, downtempo and pop from the standpoint of a producer, vocalist and band. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=trickpony",
    "sourceUrl": "https://dekmantelfestival.com/artists/trickpony-live",
    "soundcloudUrl": "https://soundcloud.com/trickponyy"
  },
  "Underground Resistance presents Depth Charge featuring Saul Williams": {
    "bio": "In techno, UR presents Depth Charge featuring Saul Williams has built a profile as a vocalist and collective. This appearance is centred on a named project, giving the project a more specific frame than a standard DJ slot. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=UR",
    "sourceUrl": "https://dekmantelfestival.com/artists/underground-resistance",
    "soundcloudUrl": "https://soundcloud.com/undergroundresistance\nhttps://soundcloud.com/saul_williams-1"
  },
  "Upsammy": {
    "bio": "upsammy is a producer operating across techno. Reference points around the act include Nous’klaer and Dekmantel Records, which helps place the music in a broader club and label context. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=upsammy",
    "sourceUrl": "https://dekmantelfestival.com/artists/upsammy-2",
    "soundcloudUrl": "https://soundcloud.com/upsammy"
  },
  "Verraco": {
    "bio": "With links to Medellín, Verraco works as a co-founder, founder and DJ in the space between techno, electro, bass and IDM. Reference points around the act include Timedance, TraTraTrax and VOAM, which helps place the music in a broader club and label context. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Verraco",
    "sourceUrl": "https://dekmantelfestival.com/artists/verraco-2",
    "soundcloudUrl": "https://soundcloud.com/verraco"
  },
  "Wata Igarashi": {
    "bio": "In techno and bass, Wata Igarashi has built a profile as a DJ. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. The result is direct enough for the dancefloor while still leaving space for detail and atmosphere.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Wata%20Igarashi",
    "sourceUrl": "https://dekmantelfestival.com/artists/wata-igarashi",
    "soundcloudUrl": "https://soundcloud.com/wata"
  },
  "Woody92": {
    "bio": "Woody92 is a DJ operating across techno, electro, minimal and rave. The profile is defined less by a single subgenre than by how those sounds are connected in sets, productions or collaborative work. That range gives the act room to move between dancefloor pressure, texture and more exploratory moments.",
    "tags": [],
    "labels": [],
    "festivals": [],
    "residentAdvisorUrl": "https://ra.co/search?search=Woody92",
    "sourceUrl": "https://dekmantelfestival.com/artists/woody92",
    "soundcloudUrl": "https://soundcloud.com/woodyninetytwo"
  }
}
